### ISSUE TITLE
Fix phone number verification

### ISSUE THREAD

**Issue by astar26** [itay-sho/LevEchad#49] opened 2020-03-26 23:15 UTC
Can't give 077 prefix (HOT)

**Comment by yoavmag** [comment] 2020-03-28 14:46
I can't reproduce it. I think its already resolved

**Comment by stavlocker** [comment] 2020-03-30 14:34
Can also confirm - tried this in development with the latest develop and it seems to work.
Close this issue?

**Comment by stavlocker** [comment] 2020-03-30 14:43
Okay, I see - this refers to the BaseHelpForm and not the VolunteerForm.

I opened issue #117 which covers this subject within it, so it's safe to close this one as the problem here is bigger (As described in the issue I opened).

**Closed** 2020-04-01 20:28 UTC
Labels: bug, good first issue
